<?php require "../logic/display-users.php" ?>

<table class="col my-5 table table-striped">
    <thead>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) {; ?>
            <tr>
                <td>
                    <?= $user["id"] ?>
                </td>
                <td>
                    <?= $user["username"] ?>
                </td>
                <td>
                    <?= $user["email"] ?>
                </td>
                <td>
                    <?= $user["password"] ?>
                </td>
                <td>
                    <?= $user["last_name"] ?>
                </td>
                <td>
                    <a href="../logic/delete-user.php?id=<?= $userData["id"]?>" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
                </td>
            </tr>
            <?php }; ?>
            
            <tr>
            <td> - </td>
            <td> - </td>
            <td> - </td>
            <td> - </td>
            <td> - </td>
            <td>
                
            </td>
        </tr>
    </tbody>
    <tfoot>
    <tr>
        <th>
            #
        </th>
        <th>
            Nom d'utilisateur
        </th>
        <th>
            Email
        </th>
        <th>
            Mot de passe
        </th>
        <th>
            Rôle
        </th>
        <th>
            Supprimer
        </th>
    </tr>
    </tfoot>
</table>